#include <brpc/channel.h>
#include <brpc/controller.h>
#include <gflags/gflags.h>

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <limits>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#include "scheduler.pb.h"

DEFINE_string(scheduler, "127.0.0.1:9100", "Scheduler address");
DEFINE_string(trace, "", "Input trace generated by generate_trace.py");
DEFINE_string(data_nodes, "", "Comma-separated managed data node IDs");
DEFINE_string(metadata_node, "", "Optional managed metadata node ID");
DEFINE_uint64(start_time_ms, 0, "Simulation epoch in milliseconds; 0 uses current time");
DEFINE_double(time_scale, 1.0, "Trace timestamp multiplier");
DEFINE_uint32(queue_depth, 1, "Queue depth attached to each event");
DEFINE_uint64(advance_after_ms, 0, "Advance simulated time beyond the final trace event");
DEFINE_bool(auto_register, true, "Register missing node IDs as simulated nodes");
DEFINE_bool(dry_run, false, "Parse and map the trace without contacting Scheduler");

namespace {

struct TraceRecord {
    uint64_t timestamp_us{0};
    std::string operation;
    std::string path;
    uint64_t offset{0};
    uint64_t size{0};
};

uint64_t NowMs() {
    using namespace std::chrono;
    return static_cast<uint64_t>(duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count());
}

std::vector<std::string> SplitNodes(const std::string& text) {
    std::vector<std::string> nodes;
    std::stringstream input(text);
    std::string item;
    while (std::getline(input, item, ',')) {
        if (!item.empty()) {
            nodes.push_back(item);
        }
    }
    return nodes;
}

uint64_t StableHash(const std::string& text) {
    uint64_t hash = 1469598103934665603ULL;
    for (unsigned char ch : text) {
        hash ^= ch;
        hash *= 1099511628211ULL;
    }
    return hash;
}

bool ParseRecord(const std::string& line, TraceRecord* record, std::string* error) {
    if (!record) {
        return false;
    }
    std::istringstream input(line);
    TraceRecord parsed;
    if (!(input >> parsed.timestamp_us >> parsed.operation >> parsed.path)) {
        if (error) {
            *error = "expected: timestamp_us op path [offset size]";
        }
        return false;
    }
    if (parsed.operation == "f_r" || parsed.operation == "f_w") {
        if (!(input >> parsed.offset >> parsed.size)) {
            if (error) {
                *error = "read/write record is missing offset or size";
            }
            return false;
        }
    } else if (parsed.operation != "f_c" && parsed.operation != "f_d" &&
               parsed.operation != "d_c" && parsed.operation != "d_l" &&
               parsed.operation != "d_d") {
        if (error) {
            *error = "unknown trace operation: " + parsed.operation;
        }
        return false;
    }
    std::string trailing;
    if (input >> trailing) {
        if (error) {
            *error = "unexpected trailing field: " + trailing;
        }
        return false;
    }
    *record = std::move(parsed);
    return true;
}

bool EnsureNode(zb::rpc::SchedulerService_Stub* stub,
                const std::string& node_id,
                zb::rpc::ManagedNodeKind kind,
                uint64_t start_time_ms,
                std::string* error) {
    zb::rpc::RegisterManagedNodeRequest request;
    auto* spec = request.mutable_spec();
    spec->set_node_id(node_id);
    spec->set_kind(kind);
    spec->set_execution_mode(zb::rpc::MANAGED_EXECUTION_SIMULATED);
    spec->set_logical_node_count(1);
    spec->set_participates_in_placement(kind == zb::rpc::MANAGED_KIND_STORAGE);
    request.set_join_time_ms(start_time_ms);
    request.set_activate_immediately(true);
    zb::rpc::ManagedNodeReply response;
    brpc::Controller controller;
    stub->RegisterManagedNode(&controller, &request, &response, nullptr);
    if (controller.Failed()) {
        if (error) {
            *error = controller.ErrorText();
        }
        return false;
    }
    if (response.status().code() != zb::rpc::SCHED_OK &&
        response.status().code() != zb::rpc::SCHED_ALREADY_EXISTS) {
        if (error) {
            *error = response.status().message();
        }
        return false;
    }
    if (response.status().code() == zb::rpc::SCHED_ALREADY_EXISTS) {
        uint32_t offset = 0;
        bool has_more = true;
        while (has_more) {
            zb::rpc::ListManagedNodesRequest list_request;
            list_request.set_include_retired(true);
            list_request.set_offset(offset);
            list_request.set_limit(1000);
            zb::rpc::ListManagedNodesReply list_response;
            brpc::Controller list_controller;
            stub->ListManagedNodes(&list_controller, &list_request, &list_response, nullptr);
            if (list_controller.Failed() || list_response.status().code() != zb::rpc::SCHED_OK) {
                if (error) {
                    *error = list_controller.Failed() ? list_controller.ErrorText()
                                                      : list_response.status().message();
                }
                return false;
            }
            for (const auto& node : list_response.nodes()) {
                if (node.spec().node_id() != node_id) {
                    continue;
                }
                if (node.spec().execution_mode() != zb::rpc::MANAGED_EXECUTION_SIMULATED ||
                    node.spec().kind() != kind ||
                    node.lifecycle() == zb::rpc::MANAGED_LIFECYCLE_RETIRED) {
                    if (error) {
                        *error = "existing node is not a compatible active simulated node";
                    }
                    return false;
                }
                return true;
            }
            has_more = list_response.has_more();
            if (list_response.next_offset() <= offset) {
                break;
            }
            offset = list_response.next_offset();
        }
        if (error) {
            *error = "existing node was not found in the managed node catalog";
        }
        return false;
    }
    return true;
}

bool SendEvent(zb::rpc::SchedulerService_Stub* stub,
               const std::string& node_id,
               const TraceRecord& record,
               uint64_t event_time_us,
               uint64_t line_number,
               bool metadata,
               std::string* error) {
    zb::rpc::ReportNodeAccessEventRequest request;
    request.set_node_id(node_id);
    request.set_event_time_us(event_time_us);
    request.set_bytes(metadata ? 0 : record.size);
    request.set_queue_depth(FLAGS_queue_depth);
    request.set_access_path(zb::rpc::MANAGED_ACCESS_DEFAULT);
    request.set_correlation_id("trace-line-" + std::to_string(line_number));
    if (!metadata && record.operation == "f_r") {
        request.set_operation(zb::rpc::MANAGED_OPERATION_READ);
    } else if (!metadata && record.operation == "f_w") {
        request.set_operation(zb::rpc::MANAGED_OPERATION_WRITE);
    } else {
        request.set_operation(zb::rpc::MANAGED_OPERATION_OTHER);
    }

    zb::rpc::ManagedNodeReply response;
    brpc::Controller controller;
    stub->ReportNodeAccessEvent(&controller, &request, &response, nullptr);
    if (controller.Failed() || response.status().code() != zb::rpc::SCHED_OK) {
        if (error) {
            *error = controller.Failed() ? controller.ErrorText() : response.status().message();
        }
        return false;
    }
    return true;
}

} // namespace

int main(int argc, char** argv) {
    google::ParseCommandLineFlags(&argc, &argv, true);
    if (FLAGS_trace.empty() || !std::isfinite(FLAGS_time_scale) || FLAGS_time_scale < 0.0) {
        std::cerr << "--trace is required and --time_scale must be non-negative" << std::endl;
        return 1;
    }
    const std::vector<std::string> data_nodes = SplitNodes(FLAGS_data_nodes);
    if (data_nodes.empty()) {
        std::cerr << "--data_nodes requires at least one node ID" << std::endl;
        return 1;
    }
    std::ifstream trace(FLAGS_trace);
    if (!trace) {
        std::cerr << "Failed to open trace: " << FLAGS_trace << std::endl;
        return 1;
    }

    const uint64_t start_time_ms = FLAGS_start_time_ms == 0 ? NowMs() : FLAGS_start_time_ms;
    if (start_time_ms > std::numeric_limits<uint64_t>::max() / 1000ULL) {
        std::cerr << "--start_time_ms is too large" << std::endl;
        return 1;
    }
    brpc::Channel channel;
    std::unique_ptr<zb::rpc::SchedulerService_Stub> stub;
    if (!FLAGS_dry_run) {
        brpc::ChannelOptions options;
        options.protocol = "baidu_std";
        options.timeout_ms = 5000;
        options.max_retry = 1;
        if (channel.Init(FLAGS_scheduler.c_str(), &options) != 0) {
            std::cerr << "Failed to connect Scheduler: " << FLAGS_scheduler << std::endl;
            return 1;
        }
        stub = std::make_unique<zb::rpc::SchedulerService_Stub>(&channel);
        if (FLAGS_auto_register) {
            std::string error;
            for (const auto& node_id : data_nodes) {
                if (!EnsureNode(stub.get(), node_id, zb::rpc::MANAGED_KIND_STORAGE, start_time_ms, &error)) {
                    std::cerr << "Failed to register " << node_id << ": " << error << std::endl;
                    return 1;
                }
            }
            if (!FLAGS_metadata_node.empty() &&
                !EnsureNode(stub.get(), FLAGS_metadata_node, zb::rpc::MANAGED_KIND_METADATA,
                            start_time_ms, &error)) {
                std::cerr << "Failed to register " << FLAGS_metadata_node << ": " << error << std::endl;
                return 1;
            }
        }
    }

    uint64_t line_number = 0;
    uint64_t parsed_records = 0;
    uint64_t metadata_events = 0;
    uint64_t data_events = 0;
    uint64_t final_event_time_us = start_time_ms * 1000ULL;
    std::string line;
    while (std::getline(trace, line)) {
        ++line_number;
        if (line.empty() || line[0] == '#') {
            continue;
        }
        TraceRecord record;
        std::string error;
        if (!ParseRecord(line, &record, &error)) {
            std::cerr << "Invalid trace line " << line_number << ": " << error << std::endl;
            return 2;
        }
        ++parsed_records;
        const long double scaled = static_cast<long double>(record.timestamp_us) * FLAGS_time_scale;
        const uint64_t base_time_us = start_time_ms * 1000ULL;
        if (scaled > static_cast<long double>(std::numeric_limits<uint64_t>::max() - base_time_us)) {
            std::cerr << "Scaled timestamp overflows at line " << line_number << std::endl;
            return 2;
        }
        const uint64_t event_time_us = base_time_us + static_cast<uint64_t>(scaled);
        final_event_time_us = std::max(final_event_time_us, event_time_us);

        if (!FLAGS_metadata_node.empty()) {
            ++metadata_events;
            if (!FLAGS_dry_run && !SendEvent(stub.get(), FLAGS_metadata_node, record,
                                             event_time_us, line_number, true, &error)) {
                std::cerr << "Metadata event failed at line " << line_number << ": " << error << std::endl;
                return 3;
            }
        }
        if (record.operation == "f_r" || record.operation == "f_w") {
            ++data_events;
            const std::string& node_id = data_nodes[StableHash(record.path) % data_nodes.size()];
            if (!FLAGS_dry_run && !SendEvent(stub.get(), node_id, record,
                                             event_time_us, line_number, false, &error)) {
                std::cerr << "Data event failed at line " << line_number << ": " << error << std::endl;
                return 3;
            }
        }
    }

    if (!FLAGS_dry_run) {
        if (FLAGS_advance_after_ms >
            (std::numeric_limits<uint64_t>::max() - final_event_time_us) / 1000ULL) {
            std::cerr << "--advance_after_ms overflows simulation time" << std::endl;
            return 4;
        }
        zb::rpc::AdvanceSimulationTimeRequest advance_request;
        advance_request.set_target_time_us(final_event_time_us + FLAGS_advance_after_ms * 1000ULL);
        zb::rpc::AdvanceSimulationTimeReply advance_response;
        brpc::Controller controller;
        stub->AdvanceSimulationTime(&controller, &advance_request, &advance_response, nullptr);
        if (controller.Failed() || advance_response.status().code() != zb::rpc::SCHED_OK) {
            std::cerr << "Failed to advance simulation time: "
                      << (controller.Failed() ? controller.ErrorText()
                                              : advance_response.status().message())
                      << std::endl;
            return 4;
        }
    }

    std::cout << "PASS records=" << parsed_records
              << " metadata_events=" << metadata_events
              << " data_events=" << data_events
              << " start_time_ms=" << start_time_ms
              << (FLAGS_dry_run ? " dry_run=true" : " dry_run=false")
              << std::endl;
    return 0;
}
